### ISSUE TITLE
Desktop App freezes

### ISSUE THREAD

**Issue by satindergrewal** [SuperNETorg/Agama#1]
seems electon limits the ulimit soft even if it’s system wide setup in both MacOS and Linux

https://github.com/electron/electron/issues/2584

It’s fixed was pushed already: https://github.com/electron/electron/pull/2642

This is what we need to do in our Electron App

https://github.com/electron/electron/blob/master/docs/api/process.md#processsetfdlimitmaxdescriptors-macos-linux

**Comment by satindergrewal** [comment]
pushed experimental commit with fix related to this issue:
https://github.com/SuperNETorg/iguana/commit/ffc6882cbdaa00b5081b1605967d5d439001aa18

testing and possible improvements required.

**Comment by ca333** [comment]
fixed. linux and OSX don't freeze anymore.
