### ISSUE TITLE
Missing input error when trying to send

### ISSUE THREAD

**Issue by osyed** [SuperNETorg/Agama#102]
When trying to send a few KMD from a wallet that has over 1000, I get this message in the txid field:

{"result":null,"error":{"code":-25,"message":"Missing inputs"},"id":"jl777","tag":"18040109768133907172"}

Wallet version is v0.1.6.2e-beta
The coin is loaded in Basilisk Mode.

Also the wallet goes in processing mode for a few minutes before showing the error.

**Comment by pbca26** [comment]
Please try pre-release version. It's already out.
