### ISSUE TITLE
xxooss

### ISSUE THREAD

**Issue by xxooss** [SuperNETorg/Agama#103]
Hello. I have a problem. I installed Agama, activated bitcoin in full mode and got a recieve address and had some coins sent to it. I can not get the program to work. I try and activate bitcoin and get it cant communicate with 127.0.0.1:7778

Then it says its not running and just keeps returning me to the start screen to activate a coin. I am running win 10 64bit on an i3 with 16gb ram. I updated java and tried opening up port 7778 and no go. Now I am worried I will never get my coins. please help.

**Comment by xxooss** [comment]
Still not able to load BTC...DGB is loading it seems.

**Comment by xxooss** [comment]
DGB starts and fails...tried it on a win 7 machine and same thing. Anybody home?

**Comment by pbca26** [comment]
Full mode is still highly volatile. Windows version has the worst performance compared to OSX or Linux. If you can use OSX/Linux that would be the best solution for now.

**Comment by xxooss** [comment]
same issue with Ubuntu...oh well.  Really should not have closed this as using another OS is not a solution.

**Comment by pbca26** [comment]
have you tried pre-release version?

**Comment by xxooss** [comment]
Yes sir I did, it was even worse on my system I did load an instance of VMware and installed Ubuntu and it is somewhat better? This tells me it is a driver issue or something in the way windows handles the network part does not work as well as the Linux drivers?
