### ISSUE TITLE
Stuck on splashscreen

### ISSUE THREAD

**Issue by Guru000** [SuperNETorg/Agama#107]
Installed Agama today on my surface pro 4, but after installing the program is stuck on the splashscreen "Starting Iguana Daemon".
Tried to restart, uninstall, without any positive result.
Everything is up-to-date on my laptop.
Working fine on my desktop PC
Note : Windows 10 creators update
![capture](https://cloud.githubusercontent.com/assets/28611666/25925541/805bfff8-35e9-11e7-9956-2c38c07f6e0f.JPG)

Thanks !

**Comment by dylanm21** [comment]
Komodo is a giant scam

**Comment by dylanm21** [comment]
this shit is a fkn scam

**Comment by dylanm21** [comment]
cd ~/Library/Application\ Support/iguana
nano config.json
skipbasisnetwork... true

**Comment by pbca26** [comment]
@Guru000
go to
C:\Program Files\AgamaApp\resources\app\assets\bin\win64
double click on iguana.exe
post here what you will get after launching iguna.exe

**Comment by Guru000** [comment]
@pcba26
"unable to launch the code, because VCRUNTIME140.dll cannot be found..."

**Comment by pbca26** [comment]
you can try this folder https://github.com/SuperNETorg/Agama/tree/master/windeps
there's a bat file that will copy required dlls to system folders
or you can copy-paste manually

**Comment by Guru000** [comment]
hmmm, then I got this message :
![capture](https://cloud.githubusercontent.com/assets/28611666/26417255/f39e5518-40b8-11e7-9a30-98280d854b21.JPG)

**Comment by pbca26** [comment]
kill any process(es) with name(s) iguana or electron in task manager
restart wallet

**Comment by Guru000** [comment]
no changes, tried to restart but same result

**Comment by pbca26** [comment]
if you see EADDRINUSE error then you didn't kill all processes
as last resort you can restart your os and launch wallet

**Comment by Guru000** [comment]
I meant I tried to restart the laptop, not the wallet.
I'm giving up, I will use the wallet on my other computer until the next update...
