### ISSUE TITLE
KMD transaction error

### ISSUE THREAD

**Issue by ydlee1227** [SuperNETorg/Agama#112]
I've send KMD to the Agama wallet

My wallet address is REZpW41DquPiufkaVffWQTUzNfmFik8Gn4

http://kmd.explorer.supernet.org/address/REZpW41DquPiufkaVffWQTUzNfmFik8Gn4

but it doesn't get any KMD after complete transaction.
Thank you for helping

**Comment by pbca26** [comment]
This is your current balance

> {
	"result": "success",
	"received": 120.44237972,
	"sent": 0,
	"balancef": 120.44237973,
	"balance": 120.44237972,
	"interest": 0.17988445,
	"height": 344012,
	"mined": 1032036,
	"randipbits": 1923364494,
	"coin": "KMD",
	"tag": "2275254921023725508"
}

You can always double check it in Atomic Explorer tab.
