### ISSUE TITLE
problem of my agama wallet

### ISSUE THREAD

**Issue by haejukz** [SuperNETorg/Agama#113]
I've send KMD bittrex to my Agama wallet today morning.

My wallet address is RRf5Lxefqf43xRrTYNTYJBh5E9C3w2hTgQ

i can check my "Total Received" at "http://kmd.explorer.supernet.org/address/RRf5Lxefqf43xRrTYNTYJBh5E9C3w2hTgQ"

but i cannot check at my Agama wallet

I do not know what the problem is.

How can I solve this problem?

Thank you for helping

**Comment by dylanm21** [comment]
Komodo is a scam

**Comment by dylanm21** [comment]
this shit is a fkn scam

**Comment by pbca26** [comment]
This is your current balance

> {
	"result": "success",
	"received": 14856.45291105,
	"sent": 0,
	"balancef": 14856.45291106,
	"balance": 14856.45291105,
	"interest": 18.72785735,
	"height": 342677,
	"mined": 1028031,
	"randipbits": 1664639832,
	"coin": "KMD",
	"tag": "7637871539760516183"
}

You can always check it on Atomic Explorer tab. Just keep pressing submit as some of Basilisk servers can have an outdated local info.
