### ISSUE TITLE
Error ps -p

### ISSUE THREAD

**Issue by porky11** [SuperNETorg/Agama#119]
`ps -p $(pidof iguana) | grep -i iguana exec error: Error: Command failed: ps -p $(pidof iguana) | grep -i iguana`
`pidof iguana` expands to nothing, since the name of the app is not iguana, but npm in case of npm start, or Agama, when using the installer version of Agama

**Comment by pbca26** [comment]
thanks for keeping an eye out
this line of code is relevant to underlying backend service
not to agama itself
