### ISSUE TITLE
KMD not showing up in agama after completed transaction

### ISSUE THREAD

**Issue by Zipbop** [SuperNETorg/Agama#124]
I recently moved some KMD to my Agama wallet. The KMD is not showing up in my Agama wallet and the transaction shows as complete. Does it have anything to deal with me on Basilisk or Full Mode in Agama? 

Wallet Address: RH2dj76sXvhPj4SxoWhw12drBkM9EHwZbH

**Comment by pbca26** [comment]
![kmd](https://cloud.githubusercontent.com/assets/7769879/26667140/5cc0beb6-46ac-11e7-9c15-82eadc73095f.jpg)

Official KMD explorer shows you transaction. Basilisk mode is still somewhat out of sync/buggy. You can check your balance as displayed on the screenshot. If you see 0 in balance field, keep pressing on "Submit" button. Eventually you will see correct balance

> {
	"result": "success",
	"received": 528.24247032,
	"sent": 0,
	"balancef": 528.24247032,
	"balance": 528.24247032,
	"interest": 0,
	"height": 344012,
	"mined": 1032036,
	"randipbits": 2736601237,
	"coin": "KMD",
	"tag": "2288158593766856205"
}

**Comment by Zipbop** [comment]
Thanks for the quick response. 

That worked thank you! balance showed in explorer and eventually updated in the actual wallet balance.
