### ISSUE TITLE
Digibyte blockchain synchronize is stuck 

### ISSUE THREAD

**Issue by sgjenks01** [SuperNETorg/Agama#125]
Digibyte blockchain synchronize has been stuck at 50.17% bundles validated. How can I get this going?  

![image](https://cloud.githubusercontent.com/assets/28461260/26737177/f1804f5e-477d-11e7-97d2-425c2fe22e22.png)

Thanks,

Steve

**Comment by pbca26** [comment]
have you tried to restart wallet?

**Comment by sgjenks01** [comment]
Numerous times. It had been saying 50.17% modules complete and now it says 50.13. Presumably because the chain has grown since it got stuck. Is there a way to delete the blockchain and start oveer?

**Comment by sgjenks01** [comment]
Where is the blockchain stored and what is it called?  I found files named data_n where n is a number sequence starting at 0 and going to 3. I the same folder (C:\Users\Steve\AppData\Roaming\Agama\Cache) has files that start with f_00000a where a is a sequence has a thru f followed by 1 to 32, etc. 

Is that where the blockchain files are stored?

**Comment by pbca26** [comment]
C:\Users\Steve\AppData\Roaming\iguana
use search to find any DGB folders
delete them
restart the wallet
once you add DGB coin again it will start syncing from the scratch

**Comment by sgjenks01** [comment]
Well, here is how I apparently solved this: I had decided to just give up on this and install the official wallet from the digibyte.org. When I did that, it took a long time to load the blockchain, but when it was done, I decided to go back and try Agama one more time. Presto, all the bars were immediately at 100%!

Problem solved.
