### ISSUE TITLE
Cannot send KMD in native mode

### ISSUE THREAD

**Issue by lux0s** [SuperNETorg/Agama#126]
I am using the latest release (Agama 0.2.0.1a) in native mode. I have syncd my node, it says 100% and all looks ok. When I then go into the 'sned' menu and try to send some funds from a transparent address to another transparent address I can click the send button, but nothin happens.

I have changed the fee to 1 KMD but the result is the same. What is happening and how can I send KMD from my wallet?

**Comment by pbca26** [comment]
do you see any records in OPID section below the send form?

**Comment by lux0s** [comment]
No, there are just two rows with the headers 
Status - ID - Time - Result

But all fields are empty. As well there is no output on the terminal with which I started Agama on the click action. With most other action there is some output there.

Btw, my platform is: Linux 4.4.0-21-generic Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Comment by pbca26** [comment]
please try new pre-release version
your send issues should be resolved by now
