### ISSUE TITLE
Balance no longer showing

### ISSUE THREAD

**Issue by Jakins55** [SuperNETorg/Agama#127]
I made a test transfer of KMD to my wallet in Basilik to test the process, all went well.
I made a second transfer of a larger sum, made successfully too.
I opened the wallet today and could see the balance. After not paying attention for an hour the balance no longer shows. Transactions in still show correctly. I have no send transactions.
I have tried restarting to no avail.
Suggestions welcome.

**Comment by Jakins55** [comment]
Panic over....funds have magically reappeared after nearly 2 hours

**Comment by Jakins55** [comment]
Arrrgh...the Balance section has gone blank again. Some kind of bug?

**Comment by Jakins55** [comment]
And back again...

**Comment by pbca26** [comment]
issues with basilisk servers
you can use this "workaround" to check balance https://github.com/SuperNETorg/Agama/issues/124
