### ISSUE TITLE
Real Time Sync Mode

### ISSUE THREAD

**Issue by sgjenks01** [SuperNETorg/Agama#129]
I declared victory a bit too soon. Agama says that all the blocks are present and validated for DGB. Now it says to wait for Real Time Sync. I have been waiting for over six hours and am still waiting for the Blue bar to turn Green! 

How long should this take?

**Comment by pbca26** [comment]
can you provide a screnshot of DGB progress on your end?

**Comment by sgjenks01** [comment]
I would have send you a screensot, except I could not get the Iguana Daemon to start. It said
Connecting to Basilisk Network... Connection status 3/8 USD. It sat there for hours.

I decided to do something a bit more drastic. I found the uninstallAgama.exe and ran that. What it didn't get rid of, I deleted including folders and registry entries that had any reference to Agama or Iguana. 

After that, I installed Agama v0.2.0.1a-beta.  When I started loading Digibyte, the status indicators were showing  about 4000 green, about 1000 yellow and zero red.

I decided to try activating Digibyte using "Sync Only". I'm not even sure if that's possible. Anyway I restarted in "Full Sync Only". So far, the process is running and the numbers are green = 340,  yellow = 0 and red = 0.

Also, I discovered you can start the same coin twice. This happened because it didn't take me into the wallet area when I restarted in sync only mode. I discovered this when I clicked on the "Display sync only coins progress, where upon I found two Digibyte coins syncing. I stopped one and it's still going.

**Comment by pbca26** [comment]
you're correct it's possible to start the same coin twice in Sync Only mode
each coin in this case runs inside a separate backend instance
full mode is still buggy but in Sync Only mode it should reach 100%
though some users reported that they couldn't

**Comment by sgjenks01** [comment]
If I start the same coin twice, does it make the progress to 100% go any faster?

I decided to try starting a different coin, so I started KMD. It's sitting where it says "Loading transaction history...". And I can see the numbers progressing just below where it says 'EASYDEX'. Those are green = ~ 60,000, red = 7 and yellow fluctuates between 0 and 2. Is the green number the Digibyte the the block count? If it is, this will take weeks to sync up because the DigiByte block height is over 4 million.

Prior to adding Komodo, I could see progress bars similar to what it looks like when the Digibyte wallet is highlighted. I got there by clicking on the link at the login screen that said "Watch progress of Sync Only coins" or something like that.  At the time I did this, there were about 38,000 green, but all of the progress bars showed zero progress. How do I get back to where I can see those progress bars again?

I can tell you what happened to create the 7 red. I decided to see if I could start a second instance of Agama. I did so by right-clicking on Agama.exe and having Windows run it in Administrator mode. It started throwing Java errors, so I killed it from task manager. I know people shouldn't try to do this, but you know they will. Is there a way to check to see if Agama is running and prevent a new instance of it from starting? I've attached the debug.log file from C:\Users\Steve\AppData\Roaming\iguana 
[debug.zip](https://github.com/SuperNETorg/Agama/files/1058953/debug.zip)
*********************
Update, 6/8 I was working on something where I had to reboot my system... Which meant I had to shut Agama down. When I started it back up, I decided to just try the KMD wallet for the time being. The KMD wallet came up nicely and synchronized quickly. The numbers in the upper left corner all went back to ZERO. 

Then I tried to send a transaction and it just sat on Processing Transaction for HOURS. The blockchain shows nothing went anywhere. 

Eventually, Agama crashed with this message: 
![captureagama error](https://user-images.githubusercontent.com/28461260/26956783-415f3110-4c75-11e7-89c4-17b862aa3c50.PNG)

And this message: 
![captureagama error2](https://user-images.githubusercontent.com/28461260/26956791-555f20ee-4c75-11e7-9346-5432764adfde.PNG)

After that, I had to kill the process with Task Manager and start over. 

Being the optimist that I am, I tried sending a transaction again, only to have it hang on "Sending Transaction". 

Where to from here, boss?

Steve

**Comment by pbca26** [comment]
you're obviously trying to make bad things happen
run the same coin twice, run several agama instances etc
your actions can lead only to one outcome which is data corruption

is KMD fully synced on your end?

**Comment by sgjenks01** [comment]
I thought the point of running/testing beta versions is to try and break it so the developer can make the product more "bullet proof". My actions should lead to you fix the code so that a user's actions won't corrupt the data. I'm just trying to help you make the code stronger. If you don't want my help, just say so. 

KMD was fully synced and Agama was only running KMD at the time I tried to withdraw some coin.  There should have been no reason for Agama to crash as it did. And it crashed twice under the exact same conditions. Since I hadn't heard from you, I switched to DGB since there was nothing new to be learned regarding KMD until you make a change. 

In the six days since I wrote my last report, I have only been running Agama in Full mode on DigiByte (no KMD and not Async.). Agama's "lights" are now 251848 Green, 0 Red and 49049 Yellow. That ratio of green to yellow has remained pretty consistently at about 5 to 1. If green represents the number of blocks, it's going to take Agama years to get synced up with DGB. Why not use a download of the blockchain to bootstrap the system?

Do those green numbers represent blocks synced? 

 I also found that if I shut Agama down, those numbers always reset to zeros when I restart it.

Does a shut down and restart mean Agama has to start over from the beginning re-syncing the entire DGB blockchain every time it is shut down?

**Comment by pbca26** [comment]
i simply explained why you see unusual behaviour
no need to over react

"lights" represent number of calls made to the backend
i'm surprised it's still running with that much of data stored in memory
if you see growing count of yellow/red "lights" that means backend service went haywire

full and native modes will resume from where you left sync process
in native it also depends which operation backend is performing at the time of shutdown

i noticed only now that you're using windows
it's unlikely that you will be able to sync any coin in full mode

**Comment by sgjenks01** [comment]
The reason the process is still running on DGB is I have 32 Gig of memory, so it has lots of room to get behind. 
Given what you just said, should I stop DGB and restart in FULL ASYNC? If not, what. 

Also, if you can think of something to try with KMD to see if I can get a transaction to go through, what might that be?

**Comment by pbca26** [comment]
full mode on windows currently is as good as dead
there's nothing that you can do apart from trying it on linux/osx

does it always lead to crash when you're trying to send KMD in native?

**Comment by sgjenks01** [comment]
Agama defaults to Basilisk mode for KMD, not Native. So that's what I have been running on KMD. I have only tried to send KMD twice, but the result was the same both times. Agama crashed and my computer ran out of memory and nearly crashed as well which is hard to do with WIN 10.

I will stop DGB now, since you say it's not going to work in Full mode on WIN. I will switch to KMD in Native mode and try to send KMD as soon as it syncs up and will let you know what happens.

Once I've done that, I will exit and switch back to running only DGB on Async.

**Comment by pbca26** [comment]
how are you sending funds in basilisk?
do you use the first toggle (alternative send)?

**Comment by sgjenks01** [comment]
I'm not able to send in Basilisk. So I am planning to use Native Mode. As I said, Agama defaults to Basilisk, so I thought that is what I should use. To answer your question, I can't remember what I did. It has been over a week since I last tried in Basilisk mode. However, as I recall, I just clicked on "send funds" and gave it an address and quantity. I don't recall seeing anything about alternative send. 

Since last I wrote, I have been trying to get the KMD wallet back in sync with the blockchain. When I just let Agama sit in native mode, I come back and find Agama back at the point where it wants my private key. This has happened twice so far. Make that 3 times now.

**Comment by sgjenks01** [comment]
Okay, so Agama finished syncing KMD using Native mode sometime last night. It is now saying that "Transaction history will be available shortly after blockchain data is synced." and has for a very long time. At this time, the green = 36486, red = 4 and yellow = 1. If there is a log you want, let me know where it is and I'll send it. 

I also tried "Atomic Explorer" to "List Unspent" for both KMD and DGB . KMD produced [ ] for Raw Output and DGB  did this:
{
	"error": "null return from iguana_bitcoinRPC",
	"tag": "16120654871536686107"
}
You've probably guessed I am doing these two currencies because I have some of each in Agama. 

I just made the mistake of exiting Agama and logging back in on KMD in Native mode. 
Apparently, the wallet has to resync. That took three days before. Does it have to grind through 3 more days just to get back where it was???

**Comment by pbca26** [comment]
no it doesn't
the wallet will resume syncing from where you left it

how many percentages does the sync bar shows?
is it 100% synced?
would be good if you can supply me with screenshots next time

**Comment by pbca26** [comment]
yes, basilisk was promoted at first but to gain all KMD features we advise to use native

**Comment by sgjenks01** [comment]
I think I see the basis of a problem here... The screenshot you sent looks nothing like mine... 
![agamakmdpng](https://user-images.githubusercontent.com/28461260/27258432-03b839ce-53af-11e7-91e4-bef928fe2203.PNG)

My application says Agama - EasyDEX (v0.5.6e-beta in the Windows banner. If I open the version file in the folders, it says v1.6.8. In either event, the app I have doesn't have the toggles you talked about. Oh, and when I look in Help => About, I get "page content goes here". Oh, and all the dates in the archive are 5/25/2017. 

Now what?

While I'm waiting for an answer to that question, I decided to try to load up Digibtyte in Full Async mode. It says it's starting, but the progress bars didn't move after at least 10 hour of running. The other odd thing is it doesn't ask me for my wallet seed. Any ideas on this front?

**Comment by pbca26** [comment]
what you you have on the screen is native mode
it has nothing to do with basilisk

sync only mode is what it says
only to download blockchain data
it runs in a separate backend instance and doesn't require seed to operate

**Comment by sgjenks01** [comment]
Okay, so please tell me exactly what to do to start Agama so that KMD will work when I try to do a transfer out. How to start, what toggles to click, right down to every move. Send screenshots if that helps.

Then tell me exactly what to do to transfer DGB out.

**Comment by sgjenks01** [comment]
You said: 
"what you you have on the screen is native mode
it has nothing to do with basilisk"
When I posted the above screenshot of the KMD wallet. 
I did that because I got part of a message on another issue (#132) in my email where you said:
![image](https://user-images.githubusercontent.com/28461260/27271179-0f4f53de-5478-11e7-8de6-329e8d78e98c.png)

After you had told me that you had switched KMD to Native mode because it supports more features, I just assumed you were talking about Native mode in the above email, not Basilisk.

Now that I have that straightened out, I tried the toggle to send using alternate method in Basilisk mode. This is what happened with that:
![image](https://user-images.githubusercontent.com/28461260/27271272-a89f9472-5478-11e7-87a6-88d394703fd5.png)
 
An update:
I got Agama to send KMD!!! I used Basilisk mode turned on the toggle "Alternative Send Method". At first it did not work so I changed the quantity and away it went. It was in my other wallet FAST. 

Now I am just stuck on DGB. I am using Full "Sync Only" and it doesn't make any progress. After 24 hours of running, I got this:
![image](https://user-images.githubusercontent.com/28461260/27403531-9e8977ec-567f-11e7-8954-d49b8baced74.png)

 At one time, this wallet was in 100% sync except the "Balances" bar. 

Are there some files I should delete to restart?

**Comment by pbca26** [comment]
if you're not using "alternative" toggle you need to fetch UTXO list first
only then you can send a transaction
we're aware that it's not intuitive
"alternative" send is recommended option to use

were you able to sync native mode or still have issues?

full mode is experimental mode and it's known not to be working well on windows
if you still want to use it i advise to install linux

**Comment by sgjenks01** [comment]
I have KMD working so I assume you are talking about DGB when you ask if I was able to sync native mode? 

Native mode is not available:
![image](https://user-images.githubusercontent.com/28461260/27493852-34b12c70-5800-11e7-913d-dc90ddc734bc.png)

I've never payed any attention to Linux. There are about 50 versions/flavors of Linux. Which particular Linux are you saying should work? A web link would be nice.

**Comment by pbca26** [comment]
no, i talk about KMD native
ubuntu 14 or 16
i use it myself

**Comment by sgjenks01** [comment]
The only mode I ever got Agama to sync KMD was using Basilisk mode, and then using the Alternative Send Method to be able to use the wallet. 

I will try Ubuntu. I have a feeling this may have a whole set of challenges for me...

**Comment by pbca26** [comment]
basilisk doesn't require sync
only full and native modes

**Comment by sgjenks01** [comment]
Okay, here is what I did: I downloaded Oracle Virtualbox. I then downloaded Ubuntu 16.4 and installed it in the virtual machine. Then I downloaded Agama for Linux/Ubuntu. The first time I started Agama, I started Komodo in Basilisk mode, and as you said, the wallet very quickly showed transactions. Next, without leaving Agama (not stopping Komodo), I started DGB in Full mode. Within a few minutes, I noticed progress bars starting to fill in! 

Shortly after that, I had a problem with virtual disk space in the VM and wound up having to completely uninstall the VM and start over. This time, I didn't start Komodo first. I started DGB in Full mode and the progress bars never started to fill. I left Agama entirely and started DGB in Full Async. Again, no progress bars...

Then it hit me that what I had done to get DGB to work the first time was to have the KMD wallet already up and running, so I completely exited Agama and restarted and started KMD in Basilisk mode (which required my wallet seed). Then I started DGB in Full mode.... And the progress bars started to fill in... 

I don't know whether having the KMD wallet loaded is the key, or having Agama "unlocked" with the seed, but it seems to me that one of those two things enabled DGB to "work". However, I'm getting about 1 yellow "light" for every 6 green lights.  The progress bars didn't move very far before they stopped advancing. 

Then I remembered that you felt DGB Full wasn't working (but maybe this only applied to Windows). Anyway, I tried to start KMD Basilisk followed by DGB full Async. At first, Agama would not start DGB in that mode. After a few tries, it started, but no DGB wallet showed up. 

Any ideas?

**Comment by pbca26** [comment]
![dgb](https://user-images.githubusercontent.com/7769879/27508984-9ca56828-58fa-11e7-8262-ece61aea2f30.png)

This is what I have on my end. All I had to do is choose DGB full mode and login with my seed. I can try to resync from the scratch but pretty sure it will sync just fine.

**Comment by sgjenks01** [comment]
Okay, based on that, I shut down Agama and restarted with DGB only running. After a bit, it showed progress bars! Then I noticed the progress bars had stopped for a few hours at 29.407 bundles. I exited again and when i came back in, the GUI then showed 34.728% almost immediately.

So, it appears that while Agama wasn't "hung", the GUI was not showing current status.  In fact I checked the Bundles % 2 hours after the restart, and it was identical to the reading at the time of the restart. So, I shut Agama down to see if it had been making progress, and sure enough, the Bundle Percent is over 35% now.

**Comment by sgjenks01** [comment]
![image](https://user-images.githubusercontent.com/28461260/27514729-2e8a4ad6-5948-11e7-9f65-2806c026e90a.png)

This far, but no further... Now what?

**Comment by pbca26** [comment]
you're almost synced
sometimes it takes a few app restarts to kickstart the progress
future versions will have improvements in this mode
right now it's a low priority task

**Comment by sgjenks01** [comment]
About how much time should it take to go from the screen shot above to get the green bar? 

How many is a "few" app restarts? (I've done 6 or so...)

I shut Agama down and restarted it. This is what I got:
![image](https://user-images.githubusercontent.com/28461260/27571810-fdf4a22e-5abc-11e7-873c-f55fe365dc3a.png)

I had to reboot the VM to get it to start Agama again.

**Comment by pbca26** [comment]
a few restarts
are you able to reproduce JavaScript error?

**Comment by sgjenks01** [comment]
No, the JavaScript error only happened once. After the reboot, everything worked fine. Oh, and the VM I had built had a 10 Gig hard drive, but apparently that wasn't big enough, so it ran out of disk space when I was at the very end. I didn't know how to give it more besides deleting everything and starting over. So, I am back to square one. The new machine has 20 Gig of Hard Drive.

**Comment by sgjenks01** [comment]
I have a question: When Agama is running, the hard drive shows at or near 100% active time. Is that normal?

**Comment by TylorRoss** [comment]
sgjenks01 please leave pbca26 alone...he is a developer not a customer service rep!!

running 2 OSs at the same time will do that shit.....duh

Install a dual boot OS Ubuntu 16.4 like the instructions say to use. I am using 17.04 because I like to break the rules!
THEN learn Ubuntu using search engines - this could take you a month - hopefully
THEN FOLLOW THESE STEPS BELOW

1 Always start with fresh installations
2. Follow instructions
3 Check to see if you followed instruction
4 Don't ask questions until you scientifically came up with a good question
5 [redacted]
6 [redacted]
7 [redacted]

A.   I just wish I could download the block chain faster or move it from a previous .komodo installation.
maybe a private key download button or something. 8-12% per hour is pretty [redacted] ridiculous...didn't zcash have a way to do that?
B.  2FA needs implemented STAT!!!.....I want my interest AND my wallets protected....

Hopefully I will be able to send some KMD tomorrow in 0.2.0.2a Native mode to a wallet that wasn't exposed to malware/virus 

I am not a whale------just a descent sized fish...

**Comment by pbca26** [comment]
@sgjenks01 in native mode while syncing the blockchain or reindexing it's expected. Native mode is quite hardware demanding.

**Comment by sgjenks01** [comment]
FYI It not only took a lot of restarts to get DGB Full to finish syncing, it too 4 or 5 restarts to get it to START syncing. Once it actually started, it finished overnight.
