### ISSUE TITLE
KMD Transaction error

### ISSUE THREAD

**Issue by blanche03** [SuperNETorg/Agama#131]
I have sent KMD to my agama wallet.
I have two addresses for one wallet seed.
But I can see only one address when I was logged in with my wallet seed.

Please refer to the withdrawal information below and let me know if you find something.

RCeREU5goS3C5pvRabXDjHYNvCzhTjvksC  total sent 1380.49723148 KMD  : It' ok
RE4r5q5GNZAYSJrTrmgF5Uphdup2xZjPqx  total sent  1380.008 KMD : I didn't received

**Comment by pbca26** [comment]
are you in control of both addresses or just one?

**Comment by blanche03** [comment]
i can see only one address in basiliak mode.
i think that i lost the another wallet seed.
How can I find another wallet seed?

**Comment by pbca26** [comment]
in your first comment you talked about two addresses in one wallet seed
now you say that it was another wallet seed
i'm confused which case was it?

**Comment by huijae7** [comment]
I also found a bug where two addresses appear in one SEED.
I think SEED will change when copying and pasting SEED stored in Windows Notepad (especially when copying / pasting SEED from Notepad into agama to log in immediately after creating the new wallet for the first time).
In the fifth test, I copied and pasted SEED when I created my new wallet. When I signed in, I did not see two addresses in one SEED (without using Windows Notepad).

**Comment by blanche03** [comment]
@pbca26 Thank you for your interest. 
In fact, this is what happened to my friend.
I wonder if there is any other way to find wallet seed when I lost wallet seed.

**Comment by pbca26** [comment]
if you enter your seed and see another address
that means the seed you're entering is different than the one you used before
there could be no other explanation to that

if you're using an old agama version not pre-release it's possible to see 2 addresses on the first login
however, your main address doesn't change
it's derived from the seed string

if you loose your seed you loose your wallet and all funds in it
