### ISSUE TITLE
Sending KMD in Basilisk Mode Forever Processing

### ISSUE THREAD

**Issue by taxationistheft69** [SuperNETorg/Agama#132]
It's in perpetual processing. Any tips? I read on the Slack channel the older versions send fine?

**Comment by pbca26** [comment]
have you tried sending with either of two options (toggles)?
at least one should work

**Comment by sgjenks01** [comment]
Please explain what you mean by option toggles. I don't see any options to toggle.

**Comment by pbca26** [comment]
![kmd-send-2-options](https://user-images.githubusercontent.com/7769879/27217484-4f21e238-527a-11e7-93e7-96812114bee4.png)

my bad
you need to pay attention only to the top most toggle
check the screenshot i attached
toggling it on is going to switch send coin method

are you using pre-release version or something older?
