### ISSUE TITLE
User is able to sign In with wrong wallet seed

### ISSUE THREAD

**Issue by gitmegha** [SuperNETorg/Agama#137]
**Steps To Reproduce:**
1. Open the app.
2. Tap on 'Activate Coin' button.
3. Select a coin [KMD] and tap on 'Activate Coin' button.
4. Tap on 'Create new wallet' button at 'welcome' screen.
5. Copy the wallet seed and paste it on 'Confirm wallet seed' text field, and tap on 'Register' button.
6. Now, enter the text randomly at 'wallet seed' text field and tap on 'Sign in' button.
7. Verify the result.

**Expected Result:**
User should not be able to sign in with wrong wallet seed.

**Actual Result:**
user is able to sign in with wrong wallet seed.

**Please consider the screencast url:**
http://www.screencast.com/t/QnoAqnRuV

**Comment by pbca26** [comment]
this is expected
any passphrase is valid
