### ISSUE TITLE
Added 'Bitcoin' wallet is not appearing on wallet list.

### ISSUE THREAD

**Issue by gitmegha** [SuperNETorg/Agama#139]
**Steps To Reproduce:**
1. Open the application.
2. Click on 'Activate Coin' button.
3. Select a coin [KMD] and click on 'Activate Coin' button.
4. Enter the 'wallet seed', and click on 'Sign in' button.
5. Now, click on 'Activate Coin' button on top of the right.
6. Select 'Bitcoin' and click on 'Activate coin'.
7. Verify the result at 'Wallet' tab.

**Expected Result:**
'Bitcoin' wallet should be appeared on wallet list.

**Actual Result:**
Added 'Bitcoin' wallet is not appearing on wallet list.

**Please consider the screencast url:**
http://www.screencast.com/t/KDsYruAL4v

**Comment by pbca26** [comment]
fixed
