### ISSUE TITLE
Added coins is not appearing on the coin list after login once close the application.

### ISSUE THREAD

**Issue by gitmegha** [SuperNETorg/Agama#140]
**Steps To Reproduce:**
1. Open the application.
2. Click on 'Activate Coin' button.
3. Select a coin [KMD] and click on 'Activate Coin' button.
4. Enter the 'wallet seed', and click on 'Sign in' button.
5. Now, click on 'Activate Coin' button on top of the right.
6. Select another coin and click on 'Activate coin' button.
7. Logout from the app and then again login with the same seed.
8. Verify added coins is appearing on the coin list.
9. Repeat the steps 5, 6 and 7 and verify added wallets is appearing on the coin list.
10. Now, close the application and again login with the same seed.
11. Verify the result.

**Expected Result:**
Added coins should be appeared on the coin list.

**Actual Result:**
Added coins is not appearing on the coin list after login once close the application.

**Please consider the screencast url:**
http://www.screencast.com/t/cFgnfza4yV2Q

**Comment by satindergrewal** [comment]
>10.Now, close the application and again login with the same seed.

Totally expected behaviour. Not a bug.
