### ISSUE TITLE
On Windows Received an error after running exe on release version 0.2.0.2a-beta. 

### ISSUE THREAD

**Issue by ricspa** [SuperNETorg/Agama#142]
* Installed the new release of the Agama Installer on  Windows.
* Release version 0.2.0.2a-beta.
* Ran the exe from desktop.
* Although the app opened successfully but  additional window opened with Java Script error.
https://www.screencast.com/t/vt6JUqyEev

* After exiting the app again a JavaScript error is received : https://www.screencast.com/t/afl0MpYXa

**Comment by TylorRoss** [comment]
Remove ALL of your old files and folders and do a clean installation. It seems like some files do not get over written.
