### ISSUE TITLE
Installer not working on linux 17.04

### ISSUE THREAD

**Issue by ricspa** [SuperNETorg/Agama#145]
# **How to Reproduce the issue**
 * Download the latest version| Version | 0.2.0.1a-beta | Date | Mon Jun 26 17:04:51 CEST 2017 |  from https://artifacts.supernet.org/latest/installer_linux.html
* After downloading the .zip file, extract the .zip file.
* After extracting the .zip file, you will get AgamaApp-0.2.0.1a-beta-linux-installer.run
* Go to the properties of .run file check the Allow executing file as program. It should be enable.
* **Graphical Method**: Click the .run file to execute 
* **Terminal Method**: 
1. Open a terminal (Applications->Accessories->Terminal).
2. Enter cd /home/user/Downloads
3. Enter chmod +x  AgamaApp-0.2.0.1a-beta-linux-installer.run
4. Enter ./ AgamaApp-0.2.0.1a-beta-linux-installer.run
(If step 4 fails with a message including 'permission denied', try entering sudo ./ AgamaApp-0.2.0.1a-beta-linux-installer.run)

# **Expected Result**
* Should have installed properly and ready to use.

**Comment by devopsacid** [comment]
In my setup it's working. Did you try run with sudo? (check my screenshot)
![screenshot from 2017-06-28 11-35-50](https://user-images.githubusercontent.com/4867436/27630674-729ded30-5bf6-11e7-914b-2d67ecacb9f6.png)
