### ISSUE TITLE
Installer: Error reading INI file Desktop.desktop

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/Agama#146]
Installed fine on ubuntu 16.04, except for this error message: 
![4c64](https://user-images.githubusercontent.com/1246198/27591912-d4112f6e-5b5b-11e7-8ea3-380179a459d3.png)

**Comment by devopsacid** [comment]
Hello. 
Did you run with sudo? (check my screenshot) 
![screenshot from 2017-06-28 11-35-50](https://user-images.githubusercontent.com/4867436/27630863-f9822b7c-5bf6-11e7-8d95-751d50e94e0d.png)

**Comment by devopsacid** [comment]
I also didn't have problem to launch application.
![screenshot from 2017-06-28 11-36-17](https://user-images.githubusercontent.com/4867436/27633204-8a70cfec-5bfe-11e7-98d2-c2658f46b93a.png)

**Comment by devopsacid** [comment]
My application shortcut is also in place:
```
~/Downloads$ ls -l ~/Desktop/Agama\ Desktop.desktop 
-rwxr-xr-x 1 nobody users 234 Jun 28 11:36 /home/max/Desktop/Agama Desktop.desktop
```
