### ISSUE TITLE
Installer not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by npkinh** [SuperNETorg/Agama#147]
**How to Reproduce the issue**

    Download the latest version AgamaApp-0.2.0.1a-beta-linux-installer.zip from https://f001.backblazeb2.com/file/supernet/files/AgamaApp-0.2.0.1a-beta-linux-installer.zip

    After downloading the .zip file, extract the .zip file.
    After extracting the .zip file, you will get AgamaApp-0.2.0.1a-beta-linux-installer.run
    Go to the properties of .run file check the Allow executing file as program. It should be enable.
    Graphical Method: Click the .run file to execute

    Terminal Method:

    Open a terminal (Applications->Accessories->Terminal).
    Enter cd /home/user/Downloads
    Enter chmod +x AgamaApp-0.2.0.1a-beta-linux-installer.run
    Enter ./ AgamaApp-0.2.0.1a-beta-linux-installer.run
     
    
**Expected Result**
         Should have installed properly and ready to use.

**Actual Result**
            Graphical Method: At the last step, there was no any installer dialog displaying.
            Terminal Method: At the last step, there was no log/error generated on terminal, it returned terminal prompt immediately.

             npkinh@kinh:~/Downloads$ ./AgamaApp-0.2.0.1a-beta-linux-installer.run 
              npkinh@kinh:~/Downloads$

**Comment by devopsacid** [comment]
Hello.
In my setup it's working. Did you try run with sudo? (check my screenshot)
![screenshot from 2017-06-28 11-35-50](https://user-images.githubusercontent.com/4867436/27630719-8e669fbc-5bf6-11e7-8dc6-bf99dfbfa1f0.png)

**Comment by npkinh** [comment]
Yes I did try but not successfully

**Comment by devopsacid** [comment]
I didn't succeed to reproduce this error. @pbca26 could you try to do?

**Comment by TylorRoss** [comment]
Remove all old installations and file folders or rename them to xxx.old..... then sudo ./AgamaApp-0.2.0.1a-beta-linux-installer.run
look in /opt and user/
I change the name from -AgamaApp-0.2.0.1a-beta-linux-installer.run to install201a.run
removing old artifacts seems to help ALL new problems

**Comment by hadjihanov** [comment]
https://komodoplatform.atlassian.net/wiki/spaces/KPSD/pages/20086807/How+to+Install+Agama+Linux
