### ISSUE TITLE
Agama in windows error

### ISSUE THREAD

**Issue by ghost** [SuperNETorg/Agama#148]
6/29/2017, 23:38:15  os_release: 10.0.15063
6/29/2017, 23:38:15  os_type: Windows_NT
6/29/2017, 23:38:15  app config set from local file
6/29/2017, 23:38:15  app started in  user mode
6/29/2017, 23:38:15  guiapp and sockets.io are listening on port 17777!
6/29/2017, 23:38:15  show loading window
6/29/2017, 23:38:15  komodo conf exists
6/29/2017, 23:38:15  found another iguana process(es)
6/29/2017, 23:38:15  taskkill /f /im iguana.exe is issued
6/29/2017, 23:38:17  app config set from local file
6/29/2017, 23:38:17  iguana flock selected...
6/29/2017, 23:38:17  selected data: none
6/29/2017, 23:38:17  confs files copied successfully at: C:\Users\ffds\AppData\Roaming\iguana\confs
6/29/2017, 23:38:17  iguana core port 7778
6/29/2017, 23:38:17  iguana core started at port 7778 pid 1624
6/29/2017, 23:38:19  show edex gui
6/29/2017, 23:38:20  iguana core fork port 7779

agama occurs error when i start agarma or active my komodo wallet

i try 0.2.0.1, 0.1.6.2e   0.1.6.1e. but every version doesn't work
(also delete config.json, shepherd folder)

![default](https://user-images.githubusercontent.com/29779165/27693461-7e24a7b4-5d24-11e7-9a60-4f6f08a7e506.jpg)

**Comment by pbca26** [comment]
is your OS 64 bit?

**Comment by ghost** [comment]
yes

**Comment by devopsacid** [comment]
we had new build of Iguana yesterday. I repack new Windows installer than you could try to download and launch new package.
