### ISSUE TITLE
[Linux] Click on "confirm" when sending has no visible effect & stuck

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/Agama#15]
IguanaApp-0.1.3-beta-linux-x64-installer.run
Basilisk mode

Tried to send KMD. When clicking on confirm it briefly displays some refreshing bar at the top (barely visible, for ~ 0.2 sec).
![peek 2017-01-31 23-29](https://cloud.githubusercontent.com/assets/1246198/22487337/40e9500c-e80d-11e6-8977-9dec1f44b2db.gif)

**Comment by satindergrewal** [comment]
New GUI solves this issue. Please comment here again if you still face the same issue.
