### ISSUE TITLE
Unable to import private key

### ISSUE THREAD

**Issue by Rhodiebert** [SuperNETorg/Agama#157]
Hello. I have a swing wallet, that shows 0,00 balance with no transactions, even though there are Komodo coins on there (the correct amount and all transactions show up, when I put in the address here: https://kmd.explorer.supernet.org/address/ ) 

Now I tried to import the private Key from this address to Agama, it says the key was imported successfully, but still the address and balance are not shown in my wallets in the Agama app. 

I use Windows 7 and followed the guide on Supernet to install both Swing and Agama. 

This is really annoying. Are Agama and Swing the only two wallets for Komodo right now?

**Comment by pbca26** [comment]
Is your Swing wallet synced to 100%?
You don't need to import your key twice as both wallets use the same wallet.dat file where all keys are stored.

**Comment by Rhodiebert** [comment]
I think it was not synced. It always stopped at around 90 - 95%. I will try to uninstall and then re install.

**Comment by pbca26** [comment]
Check what's the highest block number do you have against block height of your transaction on block explorer. You won't be able to see your transaction locally until you have the data downloaded.
