### ISSUE TITLE
Help me! what was happened to me. T_T, one KMD Seed Two address.

### ISSUE THREAD

**Issue by 3Dbeginer** [SuperNETorg/Agama#164]
I made my Agama wallet just one time.
and I copyed the Seed to my private text file with Windows notepad.

- next I copyed my KMD address. 
- and sent to my KMD address.
Address: RK5FSmMqNzWRk46R9oKUN9mZ4QSEMr2G4m 
amount: 3177.74474001
TxId: 35a05ff401904664c2578fb54829bb92dec3429c274cf703d07dbc7783178115

- next logined my Agama Seed. 
- but, KMD address changed into another address.
new Address: RBiTeQ7aU8j8DdMdY9u4HyRDhYQHgZmCMk

what happened???

I'm very embarrassed. and I want to solve this problem as soon as possible.

**Comment by 3Dbeginer** [comment]
How can I get back my KMD coin?

**Comment by pbca26** [comment]
A single passphrase produces only one address. If you haven't changed your passphrase then you should be able to access your old address. Even one extra character in the passphrase will generate a different address.

**Comment by 3Dbeginer** [comment]
If that was happened, 
How can I get back my KMD coin??

**Comment by 3Dbeginer** [comment]
![2](https://user-images.githubusercontent.com/31372093/29799422-786d31a2-8c9e-11e7-833d-c55f5707685e.png)

I did like that.

**Comment by 3Dbeginer** [comment]
I want to get back my KMDs into below address.
new Address: RBiTeQ7aU8j8DdMdY9u4HyRDhYQHgZmCMk.

I think it has a bug.

**Comment by pbca26** [comment]
Please stop creating more github tickets. It's not for user support. Head over here https://support.supernet.org and copy-paste your explanation. Someone from help support desk will help you.
