### ISSUE TITLE
Help me..

### ISSUE THREAD

**Issue by nonofol** [SuperNETorg/Agama#166]
OS: Win7 64bit
Agama: v0.2.0.2a-bata
Transactions History 
Continue loading
I am mining.
Komodo is not sent.

![6](https://user-images.githubusercontent.com/31405286/29769564-e64a80c2-8c25-11e7-8749-0351f923bc5c.png)

Please help me

**Comment by pbca26** [comment]
Mining is not recommended in basilisk mode. It will create a lot of UTXO and quickly become a problem to spend funds.

I suggest you start using KMD native and import your address there.
