### ISSUE TITLE
Funds not showing in Agama

### ISSUE THREAD

**Issue by fridoff** [SuperNETorg/Agama#169]
Hi, my KMD balance is showing zero in Agama, even though i have around 600 KMD confirmed deposited. Can you tell me how to fix this? 
thanks

**Comment by pbca26** [comment]
which mode?

**Comment by lucky626** [comment]
如果新版不能显示余额，旧版本能正常显示，

**Comment by fridoff** [comment]
it's in Basilisk mode

**Comment by ssomalia** [comment]
in Basilisk mode same problem, balance is showing zero

**Comment by ssomalia** [comment]
Agama start but still remain in sync, start only with "skipBasiliskNetworkCheck" but anyway balance is showing always zero in Basilisk mode, any suggestion?

**Comment by fridoff** [comment]
thanks @pbca26 for suggesting I type my address into http://kmd.explorer.supernet.org/. My funds do show up there (though still can't see the interest, but that's less important). @ssomalia you might want to try that.

**Comment by nicoracien** [comment]
I have the same problem with the basilisk mode... balance is wrong or 0. Use to work but not anymore...  native mode works fine

**Comment by MrChriZ** [comment]
Same here

**Comment by MrChriZ** [comment]
I've updated to v0.2.02a beta and that seems to have fixed my Basilisk problem.  However I'm now getting a lot of red errors come up!

**Comment by MrChriZ** [comment]
Ah this is because I'd not updated my config.json file as per the instructions here:
https://github.com/SuperNETorg/Agama/releases

OK this build looks fab 👍
