### ISSUE TITLE
KMD can't send money out

### ISSUE THREAD

**Issue by ongtrump** [SuperNETorg/Agama#170]
I struggle with Agamav0.2.0a-beta which I'm using for my KMD address.
It's too manny Errors.
1. Sometime it's shown Balance and sometime not shown.
2. Can't send out to another KMD Wallet.
I've used this tip but it seems not change my situation.: https://www.youtube.com/watch?v=IpLwsC8bwg4&feature=youtu.be
Anyone can help me out?

**Comment by maesitopi** [comment]
Got the same Issue.
When trying to send in Basilisk i get `couldnt create rawtx` .

**Comment by nicoracien** [comment]
Use Native mode, it works fine, but you have  to wait 24hours+ to download the blockchain. Basilisk have bugs

**Comment by aethelbert** [comment]
I use native mode but I get a different error saying komodod is down.
