### ISSUE TITLE
Unable to get it running fine on Ubuntu Xenial Linux

### ISSUE THREAD

**Issue by typoworx-de** [SuperNETorg/Agama#175]
I've followed the instructions for Linux on GIT/ReadMe.md.

I was able to get it start using "npm start". A window appears looking like a simple GUI - but all images are missing (looking like webpage having wrong path for all ressources). Buttons don't have proper functions at all.

Any idea how to fix this?

**Comment by typoworx-de** [comment]
Btw. why are there no "ready-to-run" binaries or packages provided yet?

**Comment by typoworx-de** [comment]
I was able to get a running version using this way - which does not seem to be documentated yet?

Run:
$> ./buildscripts/easydex-build.sh
$> ./buildscripts/electron-build-linux.sh
$> cd ../
$> mv build/Agama*/* ../

**Comment by typoworx-de** [comment]
I wrote a tiny build-helper named "build.sh". Still not running at all... but it builds fine and looks a lot better than build and running with description from ReadMe.md given in GIT

build.sh
```
#!/bin/bash

# Read current GIT-Tag-Version we are on!
export AGAMA_VERSION=`git describe --tags --abbrev=0`;

cd gui/EasyDEX-GUI/
git checkout master && git pull;
cd ../../

npm install;
./binary_artifacts.sh;
./check_submodule.sh;
cd buildscripts;
./easydex-build.sh;
./electron-build-linux.sh;
cd ..;

cp -R build/Agama-linux-x64/* ./;
rm -rf build/Agama-linux-x64/;

echo "Well done";
```

**Comment by typoworx-de** [comment]
Still having Ressource issues in window after starting ... no difference if starting using ./Agama nor using npm start

**Comment by nicoracien** [comment]
I use this package on ubuntu and native mode works fine for me...   https://github.com/SuperNETorg/Agama/releases/download/v0.2.0.2a-beta/Agama-linux-x64.zip    unzip and ./Agama.  Basilisk mode works but have some bugs. I was not able to run it with npm start above.
