### ISSUE TITLE
 windows javascript error 

### ISSUE THREAD

**Issue by ghost** [SuperNETorg/Agama#18]
...

**Comment by Nickardo** [comment]
[#5011](https://bitcointalk.org/index.php?topic=1605144.msg17717248#msg17717248)

Found underneath error posted on Bitcointalk on Feb 02.

PC, Windows 10, 64b. (all information provided)

![econnreset error](https://cloud.githubusercontent.com/assets/13165171/22829378/9ba0a9ae-efa2-11e6-851f-47ab73ffacab.jpg)

**Comment by satindergrewal** [comment]
The installation of app doesn't seems to happen like usual.

The expected path of .pm2 directory should be under C:\ or HOME directory of logged in User, which is again expected is to be C:\Users\ etc.

The official repo of pm2 also shows some info on it: https://github.com/Unitech/pm2/issues/1251#issuecomment-121086243

@ca333 can you please take a look. Thanks

**Comment by satindergrewal** [comment]
Please test this issue with latest installers and Agama App, if found please reopen.
