### ISSUE TITLE
Windows Crash

### ISSUE THREAD

**Issue by pondsea** [SuperNETorg/Agama#2]
![err WinInstallError](http://i.imgur.com/I8sOeBa.png)

**Comment by ca333** [comment]
@pondsea which windows are you using? did you try running as administrator?

**Comment by pondsea** [comment]
@ca333 WIndows 7 Ultimate 64bit, yes i tried administrator.

**Comment by pondsea** [comment]
I did use the VM for some other stuff, i am installing a fresh VM to see if i can replicate the issue.

**Comment by pondsea** [comment]
Fresh VM it passes

**Comment by pondsea** [comment]
Actually many people are getting this error. I suspect it is to do with the dependency conflicting with something on users machine.

**Comment by ca333** [comment]
yes - i bet it will be resolved with a "dependencies-checker" inside the iguana-app.

**Comment by satindergrewal** [comment]
Users reported to have the following installed on their machine:
http://landinghub.visualstudio.com/visual-cpp-build-tools

I tested by installing the package "windows 8.1 SDK", which took a while to install, and then tried installing "visual c++ redistributable 2015", and it was conflicting with the message saying: 

>0x80070666 - Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on Control Panel.

So, I conditioned the new Windows Installer to not prompt the user with any message in case of ANY error, even in relation to this conflict or not.

This possibly should have fixed the issue of installation. But we surely need a static binary of iguana.exe which needs the dependency files like "vcruntime140.dll" from these packages.

If "vcruntime140d.dll" is already there we don't even need to install the packaged MS installers.

**Comment by satindergrewal** [comment]
To prevent this error, we can check if the software is installed already on system using registery keys.

```shell
skerberus [10:42 AM] 
only difference between x86 and x64 might be the WOW6432Node part
in registry

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\DevDiv\VC\Servicing\14.0\RuntimeMinimum\Version

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DevDiv\VC\Servicing\14.0\RuntimeMinimum\Version

Minimum Version should be 14.0.23026
```

I tried looking for help in BitRock InstallBuilder guides, but those seems confusing.

Need help here @ca333
