### ISSUE TITLE
Start Up Alert & Multiple Windows

### ISSUE THREAD

**Issue by mickspecial** [SuperNETorg/Agama#211]
Using Mac version - Version 0.2.0.1a-beta

When open the wallet I get this as a pop up alert

> Uncaught Exception:
> TypeError: Cannot read property 'pid' of undefined
>     at /Applications/Agama.app/Contents/Resources/app/routes/shepherd.js:1711:33
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/pm2/lib/API.js:980:21
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/pm2/lib/API.js:1051:19
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/async/lib/async.js:52:16
>     at replenish (/Applications/Agama.app/Contents/Resources/app/node_modules/async/lib/async.js:314:29)
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/async/lib/async.js:330:15
>     at Object.async.forEachLimit.async.eachLimit (/Applications/Agama.app/Contents/Resources/app/node_modules/async/lib/async.js:220:35)
>     at startApps (/Applications/Agama.app/Contents/Resources/app/node_modules/pm2/lib/API.js:996:11)
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/pm2/lib/API.js:978:14
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/async/lib/async.js:52:16
>     at replenish (/Applications/Agama.app/Contents/Resources/app/node_modules/async/lib/async.js:306:28)
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/async/lib/async.js:326:29
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/async/lib/async.js:44:16
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/pm2/lib/API.js:969:18
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/pm2/lib/API.js:1305:19
>     at /Applications/Agama.app/Contents/Resources/app/node_modules/async/lib/async.js:52:16

After I click ok I sometimes then get

> Uncaught Exception:
> TypeError: Cannot read property 'destroy' of undefined
>     at Timeout._onTimeout (/Applications/Agama.app/Contents/Resources/app/node_modules/pm2/lib/Client.js:370:29)
>     at ontimeout (timers.js:365:14)
>     at tryOnTimeout (timers.js:237:5)
>     at Timer.listOnTimeout (timers.js:207:5)

Then - 3 windows open up - all the same with the ACTIVATE COIN button.

<img width="1657" alt="screen shot 2017-10-21 at 3 44 30 pm" src="https://user-images.githubusercontent.com/6512820/31848452-c2e50532-b676-11e7-81e6-a2352c679d28.png">
Start

**Comment by pbca26** [comment]
please use v0.2.0.23a
