### ISSUE TITLE
How to backup my wallet from macOS?

### ISSUE THREAD

**Issue by goldflower** [SuperNETorg/Agama#215]
Hello!

I found how to export keys on komodo support platform.

But I'm not sure if this method is also true for wallet on MAC.

I didn't see any "export keys" on my site.

<img width="1265" alt="2017-11-01 11 08 48" src="https://user-images.githubusercontent.com/7734671/32258367-14087eb8-bef5-11e7-8524-27f0e930da81.png">

What's the problem?

**Comment by pbca26** [comment]
in native mode wallet.dat is your backup
make a copy of it

**Comment by goldflower** [comment]
Thank you very much!
I also found [where is the wallet on MAC](https://support.komodoplatform.com/support/solutions/articles/29000016809-agama-2-0-23-for-mac)
