### ISSUE TITLE
Linux Installer Does Nothing

### ISSUE THREAD

**Issue by eeyang92** [SuperNETorg/Agama#255]
I just downloaded AgamaApp-0.2.025e-beta-linux.installer.zip. After extracting it and attempting to run, nothing happens. I checked the permissions and it has execution permissions.

I had luck with the .deb installer found on github a few weeks ago; however, the links seem to have been taken down now (due to instability reasons).

There are no error messages at all, so it is hard to figure out what is happening. From what I've gathered online, I am probably missing some libraries/packages on my Ubuntu system.

Is there a list of libraries/packages I should install prior to installing the wallet?

**Comment by pbca26** [comment]
try apt-get install libc6-i386 libgconf-2-4

**Comment by eeyang92** [comment]
Perfect! That worked, thank you!

**Comment by onpars** [comment]
That also worked for me. But was hard to figure out. Could you please add some error message if any package is missing?
