### ISSUE TITLE
How to delete a coin/wallets in Iguana App?

### ISSUE THREAD

**Issue by ronniem1** [SuperNETorg/Agama#35]
Hello - 

      I'm wondering if I may get some assistance with deleting coins/wallets within the Windows Iguana App?  Even after clicking on either one, I still unable to locate anything about deleting it. 

<img width="962" alt="capture" src="https://cloud.githubusercontent.com/assets/26044979/23342236/51ce5534-fc1c-11e6-9e36-1a73732d0ae3.PNG">

Thanks,
R

**Comment by pbca26** [comment]
@ronniem1 currently there's no way to remove a coin from the wallet app. It's a blocker on a backend side.
