### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by ghost** [SuperNETorg/Agama#4]
Using latest Ubuntu, I created a new account with Easydex and after I copied the seed and clicked "Register" I see a notification "Account Notification: Ops... something went wrong!" and nothing happens. But then if I enter the seed and click "Sign in" I can access the wallet and it seems to work normally. 

Update: no it doesn't seem to work normally, checking nodes from setting there are none either in basilisk or full mode

**Comment by satindergrewal** [comment]
Yes, I'm aware of this issue. The APIs needs to be updated. Expect working solution in next beta release.

**Comment by ghost** [comment]
Hi, I just tested on a fresh installed Ubuntu 16.04. I followed the instructions but there must be some minor permission issues:
1. During installation there is the following warning: "(setup:3656): IBUS-WARNING **: The owner of /home/renzo/.config/ibus/bus is not root!" but it proceeds anyway.
2. After installation the desktop link doesn't work without more permissions, the initial splash screen becomes grey and never start. I found that I need to start Iguana from command line with "sudo /opt/IguanaApp/Iguana" so it starts normally

update for v0.1.3
1. Still present but as before the app works fine
2. Still need sudo to run Iguana, I looked for how to permanently change permissions but I'm too linux noob to find the right solution
3. Install instructions on github have the text for v0.1.2

**Comment by satindergrewal** [comment]
With latest installers, the desktop icon and running iguana with `sudo` kind of issues must be fixed.

Please test again on a fresh system and reopen this issue again if problems found.

Can ignore that bus issue.
