### ISSUE TITLE
[Windows 10] Iguana crashes after adding 9 coins in Basilisk Mode

### ISSUE THREAD

**Issue by AudoKowitz** [SuperNETorg/Agama#48]
Yassin tried multiple times, always crashed with 9 coins.

![Crash screnshot](https://i.imgur.com/vs3rG2S.png)

**Comment by satindergrewal** [comment]
need steps to replicate.

**Comment by pbca26** [comment]
confirmed
max active coin limit is going to be set to 6
so only 6 coins per sessions
