### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by ghost** [SuperNETorg/Agama#5]
I tried on wife's pc with Win7 64bit and I had many issues. 
1. After default installation the desktop link didn't work, there was no iguana orange icon and it said that the link didn't exist or had been moved. I searched for the Iguana exe in my computer but couldn't find it. There was a folder with the uninstaller but even using the search function I was unable to find a folder with Iguana (or I suck at searching). At the end I uninstalled everything
2. I made a second install and during installation I selected the folder: Iguana and Iguana2 under C  so I was sure to find them. Almost at the end of installation it said there was a problem running post install step because ucrtbased.dll was missing but the installation proceeded anyway to the end. 
3. This time the desktop link had an icon and worked. The first time I tried running Iguana I encountered the same issue I found in Ubuntu: after veryfing the seed and clicking Register it said "ops... something went wrong!". Anyway I could again enter the seed and access the wallet. 
4. I started Btc in basilisk mode and the large Btc icon had the word "notarychains" instead of "bitcoin" written over it. I started also Ltc in basilisk but its icon had the usual Litecoin name
5. Even in basilisk it took a lot of CPU, almost 98% making the pc very slow and fan spinning.

I closed everything and I'll try again tomorrow.

**Comment by satindergrewal** [comment]
1. try new installer
2. try new installer
3. I'm aware of the issue. Fix will be shipped with next beta
4. I'm aware of the issue. Fix will be shipped with next beta
5. That's new. Need to know the EXACT steps to replicate. You can also ask any other users around in Slack if they experience the same issue following the exact steps that you are trying. Exact steps matters.

**Comment by satindergrewal** [comment]
Don’t change the default location of application in installation wizard. It’s not dynamic and you might get the exact errors you reported of shortcuts not working after changing install location. will look for the dynamic options later, but for now that’s how it is.

**Comment by ghost** [comment]
Tried the new installer on wife computer:
1. Same problem but I found the exe. Weird: computer has admin user called "Simona" and normal user called "Simona_2". I made installation under normal user, it says the Iguana.exe will be in IguanApp folder inside /Users/Simona_2 folder, the desktop link also points there. But at the end the IguanaApp folder wasn't there but under /Users/Simona, the admin user. 
2. Didn't happen
5. Happened again, I had only Btc in basilisk mode and cpu was working at 98%, then there was a notice that it couldn't connect to Iguana and I got log-out, I entered again and the Btc icon was missing. I added again Btc in basilisk but it said the Bitcoin was already running. I closed Iguana but from the windows task manager I saw it continued to run, I had to manually stop the process.

**Comment by ghost** [comment]
I just tried in a VM with Win7. This VM has an admin (win7pc) and a normal user (user) accounts and I installed as normal user. Again there was a mismatch, this time the installation gui said that IguanaApp will be installed under admin folder (c:\users\win7pc\iguanaapps\iguana.exe) but the desktop link points to a folder under normal user (c:\users\user\iguanaapps\iguana.exe). 

now waiting for the app to start, it seem to take forever

update: unfortunately the VM seems unble to support Iguana, the splash screen of Starting Wallet lasts forever. I tried both normal and admin user and also increased the cores from 2 to 4 but no difference.

**Comment by satindergrewal** [comment]
I discovered new bug in latest windows installer, thanks to @pondsea.
You will probably need to install "Visual C++ Redistributable for Visual Studio 2015" manually if you want to test at this stage. The new install somehow just skips it to install after downloading. will need to install both x64 and x86.
https://www.microsoft.com/en-nz/download/details.aspx?id=48145

I haven't shipped updated EasyDEX-GUI with new windows installer, only the possible fix, which seems to be behaving differently than expected.

98%+ CPU usage in just Basilisk Mode seems to be needing reported to @fadedreamz, as we are using `iguana daemon` for windows 32bit. I know the windows iguana daemon isn't perfect yet. So, expect some issues. and report them to @fadedreamz.

**Comment by ghost** [comment]
I wrote to @fadedreamz yesterday. This evening I tested the new version 1.1.2 on two Win7 64 bit, one a VM and the other my wife's computer. The results were the same and in general it worked much better than the previous time. I tested only KMD in full mode and BTC in basilisk. I found the following issues:

1. If I create a new address for KMD or BTC it creates a new address for the other coin too (or is it supposed to work this way?)
2. If I log out and log in again it doesn't save any setting, I need to select a coin again instead of just entering my seed and find the coins I already used.
3. When I re-enter the wallet I find that only the first receiving address is always the same. The new generated addresses don't get saved between sessions and when I generate them they are always different from the previous time.
4. Sometimes I get logged out when creating new addresses.
5. As previously, installing as normal user, the folder with the uninstall.exe get installed in the normal user system, while the main IguanaApp folder is in the admin user system (already told to @fadedreamz)
6. UI: I suggest to move the selection of full or basilisk mode below the coin selection, you have to pick the coin first anyway
7: UI: I suggest to delete "add coin" from the coin menu, the add-coin button in the upper right corner is enough

**Comment by satindergrewal** [comment]
1. it is supposed to happen that way
2. it is supposed to happen that way as well
3. the new generating addresses feature will be disabled for first public release. will be enabled again soon in future releases.
4. iguana.exe crashes
5. no idea what is going on. installer picks the logged in user's home directory. you must have some user/admin privilege issues or something.
6. thanks, will considering doing updates on them in next release

**Comment by satindergrewal** [comment]
both point 6 tasks are done in latest EasyDEX-GUI repo.
