### ISSUE TITLE
Opens multiple windows after loading completed (linux)

### ISSUE THREAD

**Issue by kashifali007** [SuperNETorg/Agama#55]
Running iguana wallet desktop app (linux) starts to produce multiple windows after loading completed.
the frequency is 7:10. sometime it starts to open new window after Activating a Coin but mostly it opens after loading completed.
![screenshot from 2017-03-16 19-42-37](https://cloud.githubusercontent.com/assets/16662663/24044380/d7e7bfbe-0b3c-11e7-9aea-281f8ef731a5.png)

**Comment by satindergrewal** [comment]
This issue is fixed in latest builds of Agama Desktop Wallet.
Please test and reopen this issue again if you still find any problems.
