### ISSUE TITLE
Feature Request: Specify installation directory

### ISSUE THREAD

**Issue by AudoKowitz** [SuperNETorg/Agama#67]
Make a installer where all files can be installed at a external device my main disc space is full

**Comment by satindergrewal** [comment]
This seems tricky to solve. The idea solution would be to specify path to Agama application on execution, just like with QT wallets.

like `Agama -agamadatadir="/mnt/customAgamaDir/" -komododatadir="/mnt/customKomodoDir"

Using absolute path in parameters.

**Comment by satindergrewal** [comment]
@AudoKryptowitz for that just don't use installers.
Use zip files. Extract wherever you want, and execute Agama from the extracted directory.

**Comment by satindergrewal** [comment]
@AudoKryptowitz The new installers must be able to use custom installation location.
@pedjaman told this feature has been available in test installers from weeks. So, the new installers which are public must have this feature.

Please test the custom location in Installers and verify if all works well.
Once Verified it's good, please close this issue.
Else just update if there is any problem with this action in installers.
