### ISSUE TITLE
Feature Request: Specify where each blockchain files are located

### ISSUE THREAD

**Issue by AudoKowitz** [SuperNETorg/Agama#68]
The user could specify where individual blockchain data will be downloaded and stored.

**Comment by satindergrewal** [comment]
This seems tricky to solve. The ideal solution would be to specify path to Agama application on execution, just like with QT wallets.

like `Agama -agamadatadir="/mnt/customAgamaDir/" -komododatadir="/mnt/customKomodoDir"`

Using absolute path in parameters.

**Comment by pbca26** [comment]
@AudoKryptowitz separating individual blockchain data is not possible. We don't interfere with native daemons flow. All data goes either into .iguana or .komodo folder. Moving those folders can break normal functioning.
