### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by sigwo** [SuperNETorg/Agama#74]
Windows 10, Agama Desktop 0.1.6.1e beta release
![1 6 1e-beta error](https://cloud.githubusercontent.com/assets/205676/24395207/dd4e6a38-136c-11e7-9073-cbf82c82f913.png)

**Comment by satindergrewal** [comment]
Fixed in latest commit to github. WIll be shipped with next version.
For temp fix, make a file `config.json` in `%AppData%/Iguana/` with these contents.

Linux: `~/.iguana/config.json`
OSX: `~/Library/Application Support/iguana/config.json`

```
{
"edexGuiOnly": true,
"iguanaGuiOnly": false,
"manualIguanaStart": false,
"skipBasiliskNetworkCheck": false,
"minNotaries": 50,
"host": "127.0.0.1",
"iguanaAppPort": 17777,
"iguanaCorePort": 7778,
"maxDescriptors": {
"darwin": 90000,
"linux": 1000000
}
}
```
