### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by pondsea** [SuperNETorg/Agama#8]
1. Borders at the top in windows is missing with certain resolution. On hd it works fine.

2. In atomic explorer, in drop down it should only show coins that are active. No point in displaying coins that are not active and when customer tries to call something they are told it is not active.

3. When customer clicks on Wallets and there is only 1, it should "click" into the coin by default.

4. Maybe remove the search option as there is no need for now and maybe a background colour to the menu bar.

5. Make the downloading blockchain more obvious for users. Maybe under coins it shows that it is downloading and a %.

6. At the  top "My KMD address (maybe should be changed to Komodo as that is the name of the coin) but have a copy to clip board option.

**Comment by satindergrewal** [comment]
1. that wasn't an issue.
2. will be done in next beta release. closing it here as it's Iguana Desktop repo.
3. Will have to think about it's logic and see if it's worth spending. That too will be considered for future features. This needs to be created as it's own issue on EasyDEX-GUI repo. closing here.
4. Removed it for now. Will be activated again in next beta releases soon.
5. The progress bar shows more than % info in it. I think that's enough. Showing the same percent info in the side buttons as per GUI design doesn't seem efficient enough. putting % info in sidebar buttons might slow things down. putting this to low priority, and this also needs it's own issue created in EasyDEX-GUI. closing it here.
6. Done.
