### ISSUE TITLE
wallet issue

### ISSUE THREAD

**Issue by Mrcoinzer** [SuperNETorg/Agama#83]
Hi
I have problem with my wallet Iguana
I can't send kmd to exchanges
how fix it?
I use latest version AgamaApp-0.1.6.1e-beta-win-x64

**Comment by JoelKatz** [comment]
@Mrcoinzer What version are you using? Which step do you get stuck on? What happens when you try to perform that step?

**Comment by satindergrewal** [comment]
With the latest wallet (including the next upcoming version 0.1.6.2e-beta) I could replicate the basilisk send errors after making 1 successful transaction, and the next transaction ending up in errors.

So, there is an alternative possible fix/workaround, _might be a painful_ way to get things sorted for Basilisk. Here are those:

 ```The preferred way of sending a transaction from Basilisk Mode:
- Let Basilisk Mode finish fetching data from Network on Dashboard
- After fetch data finishes, go to Send screen
- Select the address from drop down
- Enter Address in Send To field
- Enter Amount in Amount field
- Hit Send
- Hit Confirm
- Wait for the transaction to complete
- If it fails to send or complete, hit "Make Another Transaction" button to open send screen again
- On Send screen hit "Refresh Funds" button
- wait for a minute or 2
- Try sending transaction again
- If still transaction fails, go to Dashboard
- Hit Basilisk Actions > "Clear and Fetch Wallet Data" button
- Wait for a minute or 2 to fetch that data
- Go to Send Screen again
- Hit "Refresh Funds"
- Wait for a minute or 2
- Try sending a transaction again.
```

We have alternative solutions in the plan for improving Basilisk mode experience, which we are working on already.

In all scenarios, it is always preferred to use Native Mode over Basilisk Mode.

**Comment by upliftnation** [comment]
The Agama wallet seems to be really unstable and takes forever to receive or send transactions... Any idea on when the next update will be? And why does it take so long for transactions anyways?

**Comment by pbca26** [comment]
Pre-release version is already available for download. Depending on number of unspent inputs it can take anywhere from a few minutes to forever to send coins. Currently this situation is improved a bit but still we advise to use native mode. Especially if you intend to keep large amounts.

**Comment by BeEatNU** [comment]
I tried basilisk and native, I could never send any of my KMD to a exchange. 
I let it send overnight and it never sends.

Every time I try to pull down the block chain, I get DC from the software.

This is really frustrating

**Comment by mperklin** [comment]
I was unable to use the Agama wallet to send KMD either. Both Basilisk and Native mode did not work.

My balance was not shown in Agama in Basilisk mode after I entered the seed and after it fetched the wallet info. I tried resetting cache, re-fetching wallet info, and closing/restarting the app in Basilisk mode.

I switched to native mode and downloaded the chain up until the point where I saw my balance. My balance was finally shown. When I tried sending this balance (entering a destination address, entering an amount and clicking "Send") the button did not have any effect. No transaction was created or broadcast.

I waited until my native wallet completely synced and observed the same results. Clicking the "send" button did not create or broadcast any transaction.

Finally I downloaded and installed the KomodoOSX wallet. That software detected my already-downloaded blockchain from Agama and used it to display my balance immediately after opening the client. Attempting to send the KMD was successful from KomodoOSX the first time I tried it.

**Comment by ghost** [comment]
Hi all !! I hope this solution help ;) 
It's very simple, on ur Send-screen juste click/switch "alternative send method (sendtoadressapi).
It's the same, but it's just TOO fast & work ! Bye all

**Comment by Judical** [comment]
I am using the latest version and I do not see an alternative send method.

**Comment by ghost** [comment]
Agama - EasyDEX (v0.1.5.6e-beta) it's my version, and look ==> 
![sendtoapiagama](https://user-images.githubusercontent.com/19933890/27824062-7ec952b6-60ab-11e7-8dd9-f3a55cc06b9d.PNG)
