### ISSUE TITLE
Mac OS X - Agama crashes on start

### ISSUE THREAD

**Issue by pinkolin** [SuperNETorg/Agama#86]
<img width="435" alt="screenshot 2017-04-03 11 32 23" src="https://cloud.githubusercontent.com/assets/2635979/24603579/a8b2d846-1861-11e7-9134-333bd896ceeb.png">

From command line:
bash-3.2$ ./Agama
local config file is not found!

My profile:
/Users/pinky-air

**Comment by satindergrewal** [comment]
Duplicate https://github.com/SuperNETorg/Agama/issues/74#issuecomment-289701364
