### ISSUE TITLE
 Error reading INI file

### ISSUE THREAD

**Issue by phideas** [SuperNETorg/Agama#87]
Small error when installer 100%.

`Problem running post-install step. Installation may not complete correctly
 Error reading INI file /home/user/Desktop/Agama Desktop.desktop` 

Probably related to localized Ubuntu environment -> No 'Desktop' folder in my home folder.

[Screenshot](http://imgur.com/a/BsAwr)

**Comment by satindergrewal** [comment]
@pedjaman might know about it better.

**Comment by pedjaman** [comment]
Yeah, we are expecting ~/Desktop folder.
We could:
1. create it if missing
2. if no folder - do nothing.

But folder should anyway be present on most X desktops

**Comment by phideas** [comment]
Folder is there of course, just have localized name other then 'Desktop'.
It would be nice to extract and use desktop folder path from `~/.config/user-dirs.dirs` if possible:
http://askubuntu.com/questions/194124/how-to-get-language-variables-desktop-folder-name-document-folder-name-etc

**Comment by pedjaman** [comment]
point taken :)
Ok, let me see if I can push installers which will cover that issue.
Thank you for noticing ;)

**Comment by pedjaman** [comment]
@phideas I've just made pr with code which should dynamically detect Desktop folder name/path according to your comments :)
Expect it used in following releases if approved.

**Comment by phideas** [comment]
Thanks @pedjaman! Looking forward to next release. :)
