### ISSUE TITLE
Performance Bug: an increasing amount of interval checks against the dashboard and wallet

### ISSUE THREAD

**Issue by AudoKowitz** [SuperNETorg/Agama#89]
**v3miner** 
I just found kind of silly bug

Everytime you click any other tab (away from "Wallets") and then go back to Wallets and click on a wallet, it causes a whole new set of interval checks against the dashboard and wallet (edited)

In other words, it's stacking the interval calls to check the balance and *_wallet_dashboard.js (edited)

So the more you switch back and forth, the slower the entire wallet becomes over time

It's making a request to [coin]_wallet_dashboard.js and [Coin]Balance.js 53 times in row :joy:

This is because in sidebar.js you are executing KMDWalletDashboard.init() and RunKMDInitFunctions() every time a wallet icon is clicked, and compounded by not using named intervals that you can clear later. (edited)

That being said, I don't see the point of executing the init again at all since you have these intervals firing regardless of what tab you are on anyway. Should run init scripts once when the coin is added.

Oh, I should also note this will happen if you have multiple coins running, every time you switch from one coin to the other it will have the same effect

**Comment by pbca26** [comment]
new gui version will take into account this issue
