### ISSUE TITLE
[Win] Progress indicators not showing in small window size

### ISSUE THREAD

**Issue by pondsea** [SuperNETorg/Agama#9]
When my main resolution is HD, when i make the window of iguana small, i cannot see the progress bars at the bottom of the coins page. When i max the screen i can see it again.

**Comment by satindergrewal** [comment]
aware of this issue.
also tried fixing it multiple times.
might just move the progress bar on top of the screen somewhere.

**Comment by satindergrewal** [comment]
@pondsea also you are making all EasyDEX-GUI issues under Iguana Desktop Wallet repo???

**Comment by pondsea** [comment]
Dammit i am it seems :( I will close them off and move them.

**Comment by satindergrewal** [comment]
Fixed this issue. fix coming in next commit update.
