### ISSUE TITLE
Problem with wallet: Lost funds

### ISSUE THREAD

**Issue by lux0s** [SuperNETorg/Agama#99]
Hi there,

I used the pevious release Agama v0.1.6.1e-beta in Native mode to send some KMD tokens (Transparent send). I am facing some serious issues however:

- Agama in native mode stops syncing at 88.97% (I believe its the blockchain height at which I made the transaction)

- 2550 KMD have disappeared from my wallet. The id of said transaction is 196f7610b77832030c455b8fae4b12e39ddaa4886ee70b420688960aec0abca8, which shows two outputs of which only the one ending in QDsugE was intended. It seems the rest of my wallets holdings ended up in an account ending in CFZMDD, for which I do not hold the keys, nor had I ever entered this address.

- This is a major problem as I have lost more than half of my funds and my wallet is not syncing anymore, even with the new release 0.1.6.2e-beta.

I appreciate your help, Thanks

**Comment by satindergrewal** [comment]
I hope you still have your Komodo Data intact and still have wallet.dat file of komodo there.
The location of Komodo data directory is different based on OS.

Anyway, if you haven't intentionally deleted your Komodo Data directory you should still have it there.

What you reported is not a problem. It is a feature. A core feature derived from Bitcoin Core!

You'll definitely find your coins in a **"change address"**.

You should resync Komodo Native blockchain from scratch.

Open your Komodo Data directory, and ONLY delete or Move these files/folders:

```
chainstate/ blocks/ db.log debug.log fee_estimates.dat komodostate peers.dat realtime signedmasks
```

You'll have bunch of other folders, a `wallet.dat` file, and a `komodo.conf` file left.

You must have the latest Agama Wallet. Start it with Komodo Native Mode, and sync it as usual. It should finish fresh resync from scratch and you'll find your KMD in a change address.

In case of Native Komodo, all your change addresses stores in wallet.dat.

Just read on change address if want to understand it more: https://bitcoin.org/en/glossary/change-address

**Comment by lux0s** [comment]
Thanks a lot, the resync indeed did restore the funds to my wallet.

I have a few questions however:

- What caused the sync hangup? Do I have to resync every time I issue a transaction?

- In Basilisk mode the amount sent to the change address do not appear, as well the blockchain explorer gives a wrong amount of tokens for my address - whats the idea here? If this is meant as an anonymity feature it completely fails to deliver as every transaction can be traced on the blockchain anyway.

- Is it possible to issue transactions on the change address output in Basilisk mode?

- What happens if I send funds to the CFZMDD address?

Thanks a lot!
